# ##############################################################################
# Drone.io CI Configuration
#
kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: amd64
steps:
  - name: build
    image: maven:3.6.2-jdk-12
    commands:
      - java -version
      - mvn -version
      - mvn clean package
