# ##############################################################################
# Azure DevOps Pipeline [https://aka.ms/yaml]
#

pool:
  vmImage: 'ubuntu-latest'

container:
  image: maven:3.6.2-jdk-12

steps:
- checkout: self
- script: |
    java -version
    mvn -version
    mvn clean package
  displayName: 'Build'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
