# ##############################################################################
# Java Maven CircleCI 2.1
#
version: 2.1
jobs:
  build:
    docker:
      - image: maven:3.6.2-jdk-12
    working_directory: ~/project
    steps:
      - run: java -version
      - run: mvn -version
      - checkout
      - restore_cache:
          keys:
            - maven-dependencies-{{ checksum "pom.xml" }}
      - run: mvn clean package
      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-{{ checksum "pom.xml" }}
