# ##############################################################################
# Java Maven CircleCI 2.1
#
version: 2.1
jobs:
  build:
    docker:
      - image: openjdk:12.0.1
    working_directory: ~/project
    steps:
      - run: |
          sudo apt-get install maven
          java -version
          mvn -version
      - checkout
      - restore_cache:
          keys:
            - maven-dependencies-{{ checksum "pom.xml" }}
      - run: mvn clean package
      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-{{ checksum "pom.xml" }}
