# ##############################################################################
# Java Maven CircleCI 2.1
#
version: 2.1
jobs:
  build:
    docker:
      - image: openjdk:12.0.1
    working_directory: ~/project
    steps:
      - run: java -version
      - checkout
      - restore_cache:
          keys:
            - maven-dependencies-{{ checksum "pom.xml" }}
            - mvaen-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-{{ checksum "pom.xml" }}
      - run: mvn clean package
